import { COURSES,CRMState,Customer } from './domain';
export function seed():CRMState {
 const names=['ณิชา วัฒนกุล','ธนกฤต สุขเจริญ','พิมพ์ชนก อารีรัตน์','กิตติพงษ์ ใจดี','ศศิธร แสงทอง','อรพรรณ รุ่งเรือง','ธีรภัทร บุญรักษ์','มนัสนันท์ วงศ์สวัสดิ์','ภัทรพล ศรีสุข','วรัญญา สุวรรณ','ชญานิศ กุลวัฒน์','ปกรณ์ เมธากุล','อัญชลี พัฒนกิจ','นภัสสร ชัยวัฒน์','นนทกร ธรรมดี','สุชาดา พรประเสริฐ','สิรินดา ชาญชัย','ณัฐวุฒิ เกียรติชัย','จิราภา แก้วใส','พีรพล สายชล','กมลชนก ธาราทิพย์','วศิน นาคทอง','จันทิมา แสงจันทร์','ภาณุพงศ์ สุขใจ'];
 const customers:Customer[]=names.map((name,i)=>({id:`LL-${1001+i}`,name,nickname:['นิชา','ต้น','พิม','กิต','ศศิ','อร','ธีร์','มิน'][i%8],nameEn:['Nicha Wattanakul','Thanakrit Sukcharoen','Pimchanok Areerat','Kittipong Jaidee'][i%4],phone:`080000${1000+i}`,email:`learner${i+1}@example.com`,address:'99 ถนนตัวอย่าง เขตดินแดง กรุงเทพมหานคร 10400',company:i%4===0?'บริษัท ตัวอย่าง จำกัด':'',age:i===13?16:25+i,source:['LINE OA','Facebook Ads','เว็บไซต์','Instagram','แนะนำโดยเพื่อน'][i%5],landing:['/nlp-practitioner','/open-house','/master-practitioner'][i%3],owner:['เมย์','แพร','ต้น','นัท'][i%4],originOwner:i%4===3?'นัท':['เมย์','แพร','ต้น'][i%3],tags:i%3===0?['VIP','สนใจ NLP']:i%3===1?['นักเรียนใหม่']:['Alumni'],peakId:i<18?`DEMO-C${1001+i}`:'',lineId:i<20?`DEMO-U${1001+i}`:'',verified:i%5!==0,consent:i%6!==0,guardian:i===13?'คุณปาริชาติ (ผู้ปกครองสมมติ)':'',guardianConsent:i===13,interviewChild:i===13?'2026-09-12':'',interviewParent:i===13?'2026-09-12':'',created:`2026-09-${String(Math.min(28,i+3)).padStart(2,'0')}`,notes:'ข้อมูลสมมติสำหรับนำเสนอระบบ',segment:i%2===0?'พัฒนาศักยภาพ':'Alumni',sends:i===2?3:0}));
 const invoices=customers.slice(0,12).map((c,i)=>{const co=COURSES[i%4+1];return{id:`INV-2609-${String(i+1).padStart(3,'0')}`,customerId:c.id,courseId:co.id,subtotal:co.price,discount:0,vat:0,total:co.price,due:i%3===0?'2026-09-25':'2026-10-05',status:i<4?'Paid':'Partial',peakId:i<9?`DEMO-PEAK-${2001+i}`:'',kind:'Invoice'};});
 const payments=invoices.map((v,i)=>({id:`PAY-${3001+i}`,invoiceId:v.id,amount:i<4?v.total:36000,date:`2026-09-${String(i*2+3).padStart(2,'0')}`,method:i%2===0?'โอนเงิน':'2C2P',status:'Success',reference:`DEMO-TXN-${3001+i}`,submittedBy:'พนักงานบัญชี',reason:'',slip:'',settled:i<9}));
 payments.push({id:'PAY-3013',invoiceId:invoices[4].id,amount:12000,date:'2026-09-28',method:'โอนเงิน',status:'Pending',reference:'DEMO-TXN-3013',submittedBy:'พนักงานบัญชี',reason:'',slip:'สลิปตัวอย่าง (ข้อมูลสมมติ)',settled:false});
 const enrollments=invoices.slice(0,8).map((v,i)=>({id:`ENR-${4001+i}`,customerId:v.customerId,courseId:v.courseId,invoiceId:v.id,cohort:i<4?'รุ่น 28 · ก.ย. 2569':'รุ่น 29 · พ.ย. 2569',date:i<4?'2026-09-01':'2026-11-20',cutoff:'2026-11-20T12:00',progress:i<4?100:40+i*5,attendance:i<4?90:60+i*3,written:i<5,practical:i<4,adminVerified:i<4,finalApproved:i<2,cert:i===0?'SHOW':'HIDE',printed:i===0,packed:false,tracking:'',shipped:'',address:customers[i].address,alacart:true}));
 return{version:1,paymentLinks:[],deliveries:[],customers,invoices,payments,enrollments,
 leads:customers.slice(0,20).map((c,i)=>({id:`OPP-${2001+i}`,customerId:c.id,courseId:COURSES[i%5].id,owner:c.owner,stage:[0,1,2,3,4,5,6,7,8,9,0,1,0,2,1,4,5,0,1,2][i],value:COURSES[i%5].price,probability:[10,30,60,80,90,100][i%6],next:['โทรแนะนำหลักสูตร','ส่งรายละเอียดแผนผ่อน','ติดตามใบเสนอราคา'][i%3],due:i%3===0?'2026-09-27':'2026-09-30',lastContact:i%4===0?'2026-09-23':'2026-09-27',commissionRate:0})),
 cases:['ขอเปลี่ยนรอบอบรม Practitioner','ตรวจสอบยอดชำระงวดที่ 3','สอบถามการจัดส่งใบประกาศ','ขอเอกสารยินยอมผู้ปกครอง','อัปเดตข้อมูลใบกำกับภาษี','ลงทะเบียนเรียนซ้ำ'].map((title,i)=>({id:`CS-${101+i}`,customerId:customers[i].id,title,type:i===1?'การเงิน':'บริการนักเรียน',status:['New','In Progress','Waiting for Customer','New','Resolved','Closed'][i],priority:i===1?'สูง':'ปกติ',owner:['เมย์','แพร','ต้น'][i%3],due:i<2?'2026-09-27':'2026-09-30',created:'2026-09-25',comments:[],resolution:i>3?'ดำเนินการตามคำขอเรียบร้อย':'',attachments:[]})),
 tasks:['โทรติดตามแผนผ่อนชำระ','ส่งรายละเอียด NLP Practitioner','ยืนยันรอบอบรมเดือนพฤศจิกายน','ตรวจสอบที่อยู่จัดส่งใบประกาศ','นัดพูดคุยผู้ปกครอง'].map((title,i)=>({id:`TASK-${i+1}`,title,customerId:customers[i].id,owner:['เมย์','แพร','ต้น'][i%3],due:i===0?'2026-09-27':'2026-09-28',time:['09:30','10:30','13:00','14:30','16:00'][i],type:i%2===0?'โทรศัพท์':'ติดตาม',done:i===1})),
 jobs:[{id:'SYNC-01',entityId:invoices[9].id,customerId:customers[9].id,type:'Invoice',key:`peak:invoice:${invoices[9].id}`,status:'Error',attempts:2,error:'จำลอง Token หมดอายุ — กด Retry เพื่อทดสอบ',externalId:'',date:'2026-09-28T09:35:00',provider:'PEAK'},{id:'SYNC-02',entityId:invoices[8].id,customerId:customers[8].id,type:'Invoice',key:`peak:invoice:${invoices[8].id}`,status:'Success',attempts:1,error:'',externalId:invoices[8].peakId,date:'2026-09-28T09:32:00',provider:'PEAK'},{id:'SYNC-03',entityId:invoices[10].id,customerId:customers[10].id,type:'Invoice',key:`peak:invoice:${invoices[10].id}`,status:'Queued',attempts:0,error:'',externalId:'',date:'2026-09-28T09:30:00',provider:'PEAK'}],
 audit:[{id:'AUD-001',action:'อนุมัติสลิป',entity:'PAY-3012',actor:'หัวหน้าบัญชี',before:'Pending',after:'Success (Demo)',date:'2026-09-28T09:35:00'},{id:'AUD-002',action:'ยืนยันผลการเรียน',entity:'ENR-4001',actor:'ปฏิบัติการ',before:'รอยืนยัน',after:'ผ่านเกณฑ์',date:'2026-09-28T09:12:00'}],
 messages:customers.slice(0,6).flatMap((c,i)=>[{id:`MSG-${i}-1`,customerId:c.id,direction:'in',text:['สวัสดีค่ะ สนใจคอร์ส NLP Practitioner ค่ะ','แจ้งโอนชำระงวดนี้เรียบร้อยแล้วครับ','อยากสอบถามเรื่องใบประกาศค่ะ','สามารถเปลี่ยนรอบเรียนได้ไหมครับ','ขอรายละเอียด Master Practitioner เพิ่มเติมค่ะ','ขอบคุณค่ะ ได้รับเอกสารแล้ว'][i],time:`2026-09-28T0${9-i}:30:00`,status:'Received'},{id:`MSG-${i}-2`,customerId:c.id,direction:'out',text:'สวัสดีค่ะ ทีม Life Lab ยินดีดูแลนะคะ ขออนุญาตตรวจสอบข้อมูลให้ค่ะ',time:`2026-09-28T0${9-i}:31:00`,status:'Demo'}]),
 installments:['2026-09-25','2026-10-25','2026-11-25','2026-12-25','2027-01-25'].map((due,i)=>({id:`INS-0${i+1}`,invoiceId:invoices[4].id,amount:12400,due,status:'Pending',retries:i===0?2:0})),
 memberships:customers.slice(0,5).map((c,i)=>({id:`MEM-${i+1}`,customerId:c.id,type:'hypno.club',expiry:i<2?'2026-10-02':'2027-05-01',status:'Active'})),
 staff:[{id:'U01',name:'วิวี่',email:'executive@example.com',roles:['ผู้บริหาร'],status:'Active'},{id:'U02',name:'เมย์',email:'may@example.com',roles:['ฝ่ายขาย'],status:'Active'},{id:'U03',name:'แพร',email:'prae@example.com',roles:['หัวหน้าฝ่ายขาย'],status:'Active'},{id:'U04',name:'ต้น',email:'ton@example.com',roles:['ปฏิบัติการ'],status:'Active'},{id:'U05',name:'นัท',email:'nat@example.com',roles:['เซลล์ภายนอก'],status:'Active'},{id:'U06',name:'ขวัญ',email:'kwan@example.com',roles:['พนักงานบัญชี'],status:'Pending'}],
 automations:[{id:'AUTO-1',name:'เตือนก่อนครบกำหนดชำระ',trigger:'วันครบกำหนดงวด',channel:'LINE OA + ในระบบ',days:3,enabled:true,template:'สวัสดีคุณ {{name}} ยอดชำระ {{amount}} บาท ครบกำหนดวันที่ {{due}} ขอบคุณค่ะ',version:1},{id:'AUTO-2',name:'ติดตาม Lead ที่เงียบ',trigger:'ไม่มีการติดต่อ',channel:'ในระบบ · เจ้าของ Lead',days:3,enabled:true,template:'ติดตาม {{name}} ซึ่งไม่มีการติดต่อล่าสุด',version:1},{id:'AUTO-3',name:'ต่ออายุ hypno.club',trigger:'วันหมดอายุสมาชิก',channel:'LINE OA',days:5,enabled:true,template:'สมาชิก hypno.club ของคุณ {{name}} จะหมดอายุวันที่ {{due}} ต่ออายุด้วยการโอน 432 บาท',version:1}],refunds:[],campaignLog:[],migrationRuns:[]};
}
