'use client';
import { Sidebar,SidebarContent,SidebarFooter,SidebarGroup,SidebarHeader,SidebarInset,SidebarMenu,SidebarMenuButton,SidebarMenuItem,SidebarProvider,SidebarTrigger,useSidebar } from '@/components/ui/sidebar';
import { canViewPage } from '@/lib/crm/access';
import { Customer,ROLES,duplicateCustomer,uid } from '@/lib/crm/domain';
import { Bell,CalendarDays,ChartNoAxesCombined,ChevronDown,ChevronRight,GitBranch,GraduationCap,History,LayoutDashboard,Megaphone,MessageCircle,Moon,Plug,Search,Settings,ShieldCheck,Sparkles,Sun,Ticket,Users,Wallet,Zap } from 'lucide-react';
import { lazy,Suspense,useEffect,useState } from 'react';
import { Toaster,toast } from 'sonner';
const Team=lazy(()=>import('./admin').then(m=>({default:m.Team})));
const AuditLog=lazy(()=>import('./admin').then(m=>({default:m.AuditLog})));
const SettingsPage=lazy(()=>import('./admin').then(m=>({default:m.Settings})));
import Customers,{ CustomerSheet } from './customers';
import Dashboard from './dashboard';
const Inbox=lazy(()=>import('./engagement').then(m=>({default:m.Inbox})));
const Marketing=lazy(()=>import('./engagement').then(m=>({default:m.Marketing})));
const Automations=lazy(()=>import('./engagement').then(m=>({default:m.Automations})));
const Finance=lazy(()=>import('./finance'));
const Integrations=lazy(()=>import('./integrations'));
const Learning=lazy(()=>import('./learning'));
const Reports=lazy(()=>import('./reports'));
const Pipeline=lazy(()=>import('./sales').then(m=>({default:m.Pipeline})));
const Cases=lazy(()=>import('./sales').then(m=>({default:m.Cases})));
const Activities=lazy(()=>import('./sales').then(m=>({default:m.Activities})));
import { Provider,useCRM } from './store';
import { Avatar,Button,FormModal,Pick,Pill } from './ui';
import WebTools from './web-tools';
const NAV: {label:string;items:[string,string,typeof Users][]}[]=[{label:'พื้นที่ทำงาน',items:[['dashboard','ภาพรวมธุรกิจ',LayoutDashboard],['customers','ลูกค้า Customer 360',Users],['pipeline','Sales Pipeline',GitBranch],['cases','เคสและบริการ',Ticket],['activities','กิจกรรมและปฏิทิน',CalendarDays]]},{label:'เชื่อมต่อการทำงาน',items:[['finance','การเงินและการชำระ',Wallet],['learning','คอร์สและใบประกาศ',GraduationCap],['inbox','กล่องข้อความ LINE',MessageCircle],['marketing','การตลาดและแคมเปญ',Megaphone],['automation','ระบบอัตโนมัติ',Zap],['reports','รายงานและวิเคราะห์',ChartNoAxesCombined]]},{label:'จัดการระบบ',items:[['integrations','การเชื่อมต่อ',Plug],['team','ทีมและสิทธิ์ใช้งาน',ShieldCheck],['audit','ประวัติการทำงาน',History],['settings','ตั้งค่าและนำเข้าข้อมูล',Settings]]}];
export default function CRM(){return <Provider><SidebarProvider style={{'--sidebar-width':'246px'} as React.CSSProperties}><Workspace/></SidebarProvider></Provider>;}
function Workspace(){
 const{state,page,go,role,setRole,customers,inspect,mutate}=useCRM();const{setOpenMobile}=useSidebar();
 const[theme,setTheme]=useState(()=>{try{return localStorage.getItem('lifelab-theme')==='dark'?'dark':'light';}catch{return 'light';}}),[search,setSearch]=useState(''),[create,setCreate]=useState(false),[notifications,setNotifications]=useState(false);
 useEffect(()=>{document.documentElement.classList.toggle('dark',theme==='dark');document.documentElement.dataset.theme=theme;try{localStorage.setItem('lifelab-theme',theme);}catch{/* Theme still works when storage is disabled. */}},[theme]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();document.querySelector<HTMLInputElement>('[aria-label="ค้นหาลูกค้าทั่วระบบ"]')?.focus();}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);
 const navigate=(p:string)=>{go(p);setOpenMobile(false);};
 const title=NAV.flatMap(n=>n.items).find(n=>n[0]===page)?.[1]||'ภาพรวมธุรกิจ';
 const allowed=(id:string)=>canViewPage(role,id);
 return <><Sidebar className="app-sidebar"><SidebarHeader className="brand"><div className="brand-mark">L<span>L</span></div><div><strong>life<span>lab</span><small>CRM</small></strong><p>ACADEMY WORKSPACE</p></div></SidebarHeader><div className="workspace-switch"><span className="workspace-avatar">L</span><div><b>Life Lab Academy</b><small>พื้นที่ทำงานของทีม</small></div><ChevronDown size={15}/></div><SidebarContent>{NAV.map(group=><SidebarGroup key={group.label}><div className="nav-label">{group.label}</div><SidebarMenu>{group.items.filter(([id])=>allowed(id)).map(([id,label,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton isActive={page===id} onClick={()=>navigate(id)} className="nav-button"><Icon/><span>{label}</span>{id==='inbox'&&<span className="nav-count">6</span>}{id==='integrations'&&state.jobs.some(j=>j.status==='Error')&&<span className="nav-alert"/>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup>)}</SidebarContent><SidebarFooter><div className="demo-card"><div><Sparkles size={17}/><b>Presentation mode</b></div><p>ทดลองทุกขั้นตอนด้วยข้อมูลสมมติ</p><span>DEMO WORKSPACE <span>v1.0</span></span></div><div className="sidebar-person"><Avatar name="วิวี่"/><div><b>{role==='ผู้บริหาร'?'วิวี่ · Life Lab':role}</b><small>{role==='ผู้บริหาร'?'Executive workspace':'มุมมองบทบาท · เดโม'}</small></div><span className="status-dot"/></div></SidebarFooter></Sidebar>
 <SidebarInset className="workspace-main"><header className="topbar"><div className="breadcrumb"><SidebarTrigger/><span className="breadcrumb-root">Workspace</span><ChevronRight size={14}/><b>{title}</b></div><div className="topbar-tools"><div className="global-search"><Search size={16}/><input placeholder="ค้นหาลูกค้า..." aria-label="ค้นหาลูกค้าทั่วระบบ" value={search} onChange={e=>setSearch(e.target.value)}/><kbd>⌘ K</kbd>{search&&<div className="search-results">{customers.filter(c=>`${c.name} ${c.phone} ${c.email} ${c.id}`.toLowerCase().includes(search.toLowerCase())).slice(0,6).map(c=><button key={c.id} onClick={()=>{inspect(c.id);setSearch('');}}><Avatar name={c.name}/><span>{c.name}<small>{c.id}</small></span></button>)}{!customers.some(c=>`${c.name} ${c.phone} ${c.email} ${c.id}`.toLowerCase().includes(search.toLowerCase()))&&<p>ไม่พบลูกค้า</p>}</div>}</div><button className="icon-button theme-toggle" aria-label={theme==='light'?'เปลี่ยนเป็น Dark mode':'เปลี่ยนเป็น Light mode'} onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={19}/>:<Sun size={19}/>}</button><div className="notifications-wrap"><button className="icon-button notification-bell" aria-label="การแจ้งเตือน" onClick={()=>setNotifications(!notifications)}><Bell size={19}/><i/></button>{notifications&&<div className="notification-pop"><h3>สิ่งที่ต้องดูแล</h3>{[['finance','รอตรวจสอบสลิป',state.payments.filter(p=>p.status==='Pending').length],['cases','เคสที่ยังเปิดอยู่',state.cases.filter(c=>c.status!=='Closed').length],['integrations','PEAK ต้องตรวจสอบ',state.jobs.filter(j=>j.status==='Error').length]].filter(([id])=>allowed(String(id))).map(([id,text,count])=><button key={id} onClick={()=>{navigate(String(id));setNotifications(false);}}><span>{text}</span><Pill tone="orange">{count}</Pill></button>)}</div>}</div><div className="header-divider"/><Avatar name="วิวี่" size="small"/></div></header>
 <div className="role-ribbon"><span><span className="demo-indicator"/> DEMO <span className="ribbon-copy">ข้อมูลสมมติ · ไม่ส่งรายการไปยังระบบภายนอก</span></span><div><span>มุมมอง</span><Pick value={role} onChange={setRole} options={[...ROLES,'ฝ่ายขาย + ปฏิบัติการ']} label="เลือกบทบาทเดโม"/></div></div>
 <section className="page-content" aria-label="พื้นที่ทำงาน CRM"><Suspense fallback={<div className="empty" role="status">กำลังเปิดหน้าจอ…</div>}>{!allowed(page)?<div className="panel p-8"><h1>บทบาทนี้ไม่มีสิทธิ์เข้าหน้านี้</h1><p>เลือกเมนูที่อยู่ในขอบเขต หรือสลับบทบาทเดโมที่แถบด้านบน</p><Button className="mt-4" onClick={()=>go('dashboard')}>กลับภาพรวม</Button></div>:page==='dashboard'?<Dashboard createCustomer={()=>setCreate(true)}/>:page==='customers'?<Customers create={()=>setCreate(true)}/>:page==='pipeline'?<Pipeline/>:page==='cases'?<Cases/>:page==='activities'?<Activities/>:page==='finance'?<Finance/>:page==='learning'?<Learning/>:page==='inbox'?<Inbox/>:page==='marketing'?<Marketing/>:page==='automation'?<Automations/>:page==='integrations'?<Integrations/>:page==='reports'?<Reports/>:page==='team'?<Team/>:page==='audit'?<AuditLog/>:page==='settings'?<SettingsPage/>:<Dashboard createCustomer={()=>setCreate(true)}/>}</Suspense></section>
 </SidebarInset><CustomerSheet/><WebTools/><Toaster richColors position="bottom-right"/>
 {create&&<FormModal title="เพิ่มลูกค้าใหม่" description="ตรวจสอบชื่อ เบอร์โทร และอีเมลซ้ำก่อนบันทึก" fields={[{key:'name',label:'ชื่อ–นามสกุล',required:true},{key:'phone',label:'เบอร์โทร',type:'tel',required:true},{key:'email',label:'อีเมล',type:'email',required:true},{key:'nickname',label:'ชื่อเล่น'},{key:'age',label:'อายุ',type:'number',min:0,max:120,value:25,required:true},{key:'landing',label:'Landing Page'},{key:'owner',label:'ผู้ดูแล',options:['เมย์','แพร','ต้น','นัท'],value:'เมย์',required:true},{key:'source',label:'ช่องทาง',options:['LINE OA','Facebook Ads','Instagram','เว็บไซต์','แนะนำโดยเพื่อน'],value:'LINE OA',required:true}]} onSave={v=>{const duplicate=duplicateCustomer(state.customers,{name:v.name,phone:v.phone,email:v.email});if(duplicate)throw Error(`พบโปรไฟล์เดิม ${duplicate.name} (${duplicate.id}) กรุณาใช้โปรไฟล์เดิม`);const id=uid('LL');mutate('สร้างลูกค้า',id,s=>{s.customers.unshift({id,...v,name:v.name,phone:v.phone,email:v.email,nickname:v.nickname,owner:v.owner,source:v.source,nameEn:'',address:'',company:'',age:Number(v.age),originOwner:v.owner,tags:['นักเรียนใหม่'],peakId:'',lineId:'',verified:false,consent:false,guardian:'',guardianConsent:false,interviewChild:'',interviewParent:'',created:'2026-09-28',notes:'',segment:'พัฒนาศักยภาพ',sends:0,landing:v.landing||''} as Customer);});toast.success('เพิ่มลูกค้าแล้ว');}} onClose={()=>setCreate(false)}/>}</>;
}
