'use client';
import { Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle } from '@/components/ui/sheet';
import { Switch } from '@/components/ui/switch';
import { COURSES,STAGES,baht,balanceFor,dateTH,duplicateCustomer,paidFor } from '@/lib/crm/domain';
import { ArrowUpRight,ChevronLeft,ChevronRight,Download,Mail,MapPin,Merge,Pencil,Phone,Plus,ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import { toast } from 'sonner';
import { useCRM } from './store';
import { Avatar,Button,Cell,DataTable,Empty,Field,FormModal,Panel,Pick,Pill,Row,SearchBox,Status,TabBar,Title,exportCSV } from './ui';
export default function Customers({create}:{create:()=>void}){
 const{customers,state,inspect,mutate,role}=useCRM();const[q,setQ]=useState(''),[source,setSource]=useState('all'),[owner,setOwner]=useState('all'),[sort,setSort]=useState('new'),[page,setPage]=useState(1);
 const rows=customers.filter(c=>(source==='all'||c.source===source)&&(owner==='all'||c.owner===owner)&&`${c.name} ${c.nickname} ${c.phone} ${c.email} ${c.id} ${c.lineId} ${c.peakId} ${c.tags.join(' ')} ${state.invoices.filter(i=>i.customerId===c.id).map(i=>i.id).join(' ')}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,'th'):b.created.localeCompare(a.created));
 const max=Math.max(1,Math.ceil(rows.length/8)),current=Math.min(page,max);const shown=rows.slice((current-1)*8,current*8);
 const exportRows=()=>{exportCSV('lifelab-customers',['รหัส','ชื่อ','เบอร์โทร','อีเมล','ช่องทาง','ผู้ดูแล'],rows.map(c=>[c.id,c.name,c.phone,c.email,c.source,c.owner]));mutate('ส่งออก CSV','customers',()=>{});};
 return <><Title eyebrow="PEOPLE & RELATIONSHIPS" title="ลูกค้า Customer 360" desc="ทุกบทสนทนา ทุกความคืบหน้า เชื่อมอยู่ในโปรไฟล์เดียว"><Button variant="outline" onClick={exportRows} disabled={role==='เซลล์ภายนอก'}><Download size={16}/> ส่งออก</Button><Button onClick={create} disabled={['การตลาด','หัวหน้าบัญชี','พนักงานบัญชี','เซลล์ภายนอก'].includes(role)}><Plus size={17}/> เพิ่มลูกค้า</Button></Title><div className="summary-chips"><span>ลูกค้าทั้งหมด <b>{customers.length}</b></span><span>ยืนยันตัวตนแล้ว <b>{customers.filter(c=>c.verified).length}</b></span><span>อนุญาตการตลาด <b>{customers.filter(c=>c.consent).length}</b></span><span>ผู้เยาว์ <b>{customers.filter(c=>c.age<20).length}</b></span></div><Panel><div className="toolbar"><SearchBox value={q} onChange={v=>{setQ(v);setPage(1);}} placeholder="ค้นหาชื่อ เบอร์โทร รหัส หรือ Tag"/><Pick label="กรองช่องทาง" value={source} onChange={v=>{setSource(v);setPage(1);}} options={[{value:'all',label:'ทุกช่องทาง'},'LINE OA','Facebook Ads','Instagram','เว็บไซต์','แนะนำโดยเพื่อน']}/><Pick label="กรองผู้ดูแล" value={owner} onChange={setOwner} options={[{value:'all',label:'ผู้ดูแลทั้งหมด'},'เมย์','แพร','ต้น','นัท']}/><Pick label="เรียงลำดับ" value={sort} onChange={setSort} options={[{value:'new',label:'ล่าสุดก่อน'},{value:'name',label:'ชื่อ ก–ฮ'}]}/></div><DataTable heads={['ลูกค้า','ข้อมูลติดต่อ','ช่องทาง','กลุ่มลูกค้า','ผู้ดูแล','การยืนยัน','']}>
 {shown.map(c=><Row key={c.id}><Cell><button className="person person-link" onClick={()=>inspect(c.id)}><Avatar name={c.name}/><span><b>{c.name}</b><small>{c.id} · {c.nickname}</small></span></button></Cell><Cell><span>{c.phone}</span><small className="block muted">{c.email}</small></Cell><Cell>{c.source}</Cell><Cell><div className="tag-list">{c.tags.map(t=><Pill key={t} tone={t==='VIP'?'orange':'purple'}>{t}</Pill>)}</div></Cell><Cell>{c.owner}</Cell><Cell><Pill tone={c.verified?'green':'neutral'}>{c.verified?'ยืนยันแล้ว':'รอยืนยัน'}</Pill></Cell><Cell><button className="icon-button" aria-label={`ดูโปรไฟล์ ${c.name}`} onClick={()=>inspect(c.id)}><ArrowUpRight size={17}/></button></Cell></Row>)}</DataTable>{!shown.length&&<Empty/>}<div className="table-footer"><span>แสดง {rows.length?(current-1)*8+1:0}–{Math.min(current*8,rows.length)} จาก {rows.length} รายการ</span><div><Button variant="outline" size="sm" disabled={current<=1} onClick={()=>setPage(current-1)} aria-label="หน้าก่อนหน้า"><ChevronLeft size={15}/></Button><span>{current} / {max}</span><Button variant="outline" size="sm" disabled={current>=max} onClick={()=>setPage(current+1)} aria-label="หน้าถัดไป"><ChevronRight size={15}/></Button></div></div></Panel></>;
}
export function CustomerSheet(){
 const{selected,setSelected,customers,state,finance,executive,mutate,role}=useCRM();const[tab,setTab]=useState('overview'),[edit,setEdit]=useState(false),[merge,setMerge]=useState(false);const c=customers.find(c=>c.id===selected);
 if(!c)return null;
 const invoices=state.invoices.filter(i=>i.customerId===c.id),enrollments=state.enrollments.filter(e=>e.customerId===c.id),cases=state.cases.filter(x=>x.customerId===c.id),leads=state.leads.filter(x=>x.customerId===c.id);
 const fields:Field[]=[{key:'name',label:'ชื่อ–นามสกุล',value:c.name,required:true},{key:'nickname',label:'ชื่อเล่น',value:c.nickname},{key:'nameEn',label:'ชื่อ–นามสกุลภาษาอังกฤษ',value:c.nameEn},{key:'age',label:'อายุ',type:'number',value:c.age,min:0,max:120,required:true},{key:'phone',label:'เบอร์โทร',value:c.phone,required:true},{key:'email',label:'อีเมล',type:'email',value:c.email,required:true},{key:'company',label:'นิติบุคคล',value:c.company},{key:'owner',label:'ผู้ดูแล',value:c.owner,options:['เมย์','แพร','ต้น','นัท'],required:true},{key:'source',label:'แหล่งที่มา',value:c.source,options:['LINE OA','Facebook Ads','Instagram','เว็บไซต์','แนะนำโดยเพื่อน']},{key:'landing',label:'Landing Page',value:c.landing},{key:'address',label:'ที่อยู่',type:'textarea',value:c.address,full:true},{key:'guardian',label:'ผู้ปกครอง',value:c.guardian},{key:'guardianConsent',label:'ความยินยอมผู้ปกครอง',value:c.guardianConsent?'yes':'no',options:[{value:'yes',label:'ได้รับแล้ว'},{value:'no',label:'ยังไม่ได้รับ'}]},{key:'interviewChild',label:'วันที่สัมภาษณ์เด็ก',type:'date',value:c.interviewChild},{key:'interviewParent',label:'วันที่สัมภาษณ์ผู้ปกครอง',type:'date',value:c.interviewParent}];
 const tabs=[{id:'overview',label:'ภาพรวม'},{id:'sales',label:'การขาย'},...(finance?[{id:'finance',label:'การเงิน'}]:[]),{id:'learning',label:'การเรียน'},{id:'cases',label:'เคส'},{id:'messages',label:'LINE'},{id:'files',label:'เอกสาร'},{id:'tasks',label:'กิจกรรม'},{id:'history',label:'ประวัติ'}];
 return <Sheet open={!!selected} onOpenChange={v=>{if(!v){setSelected('');setTab('overview');}}}><SheetContent className="customer-sheet"><SheetHeader><SheetTitle>Customer 360</SheetTitle><SheetDescription>โปรไฟล์ลูกค้า · {c.id}</SheetDescription></SheetHeader><div className="profile-hero"><Avatar name={c.name} size="large"/><div><h2>{c.name}</h2><p>{c.nickname} · {c.age} ปี</p><div className="tag-list">{c.tags.map(t=><Pill tone="purple" key={t}>{t}</Pill>)}</div></div>{executive&&<Button size="sm" variant="outline" onClick={()=>setEdit(true)}><Pencil size={14}/> แก้ไข</Button>}</div><div className="profile-body"><TabBar value={tab} onChange={setTab} items={tabs}/>
 {tab==='overview'&&<><div className="profile-contact"><p><Phone size={16}/>{c.phone}</p><p><Mail size={16}/>{c.email}</p><p><MapPin size={16}/>{c.address||'ยังไม่มีที่อยู่'}</p></div><div className="detail-grid"><div><small>ชื่อภาษาอังกฤษ</small><b>{c.nameEn||'—'}</b></div><div><small>ผู้ดูแล</small><b>{c.owner}</b></div><div><small>แหล่งที่มา</small><b>{c.source}</b></div><div><small>Landing Page</small><b>{c.landing||'—'}</b></div><div><small>PEAK Customer ID</small><b>{c.peakId||'ยังไม่เชื่อม'}</b></div><div><small>LINE User ID</small><b>{c.lineId||'ยังไม่เชื่อม'}</b></div><div><small>นิติบุคคล</small><b>{c.company||'บุคคลธรรมดา'}</b></div><div><small>OTP</small><b>{c.verified?'ยืนยันแล้ว':'รอยืนยัน'}</b></div></div><div className="consent-card"><ShieldCheck size={22}/><div><b>ความยินยอมการตลาด</b><p>หยุดหรืออนุญาตทั้ง LINE OA และอีเมลพร้อมกัน</p></div><Switch aria-label="ความยินยอมการตลาด" checked={c.consent} disabled={!executive&&role!=='การตลาด'} onCheckedChange={v=>mutate('เปลี่ยนความยินยอม',c.id,s=>{s.customers.find(x=>x.id===c.id)!.consent=v;})}/></div>{c.age<20&&<div className="info-box"><b>ข้อมูลผู้เยาว์</b><p>ผู้ปกครอง: {c.guardian||'ยังไม่ระบุ'} · {c.guardianConsent?'ยินยอมแล้ว':'รอความยินยอม'}</p><p>สัมภาษณ์เด็ก: {dateTH(c.interviewChild)} · ผู้ปกครอง: {dateTH(c.interviewParent)}</p><small>เก็บเฉพาะสถานะและวันที่สัมภาษณ์</small></div>}{executive&&<Button variant="outline" className="mt-5" onClick={()=>setMerge(true)}><Merge size={15}/> รวมโปรไฟล์ซ้ำ</Button>}</>}
 {tab==='sales'&&<div className="detail-list">{leads.map(l=><article key={l.id}><div><b>{COURSES.find(x=>x.id===l.courseId)?.name}</b><small>{l.id} · ผู้ดูแล {l.owner}</small></div><Pill tone="purple">{STAGES[l.stage]}</Pill><p>งานถัดไป: {l.next}</p><p>ปิดคาดการณ์ {dateTH(l.due)} · โอกาส {l.probability}%</p></article>)}{!leads.length&&<Empty text="ยังไม่มีโอกาสขาย"/>}</div>}
 {tab==='finance'&&finance&&<div className="detail-list">{invoices.map(i=><article key={i.id}><div><b>{i.id}</b><Status value={balanceFor(state,i.id)===0?'Paid':'Partial'}/></div><p>ยอดสุทธิ {baht(i.total)} · ชำระแล้ว {baht(paidFor(state,i.id))}</p><strong>คงเหลือ {baht(balanceFor(state,i.id))}</strong><small>PEAK: {i.peakId||'รอซิงก์'}</small></article>)}{!invoices.length&&<Empty/>}</div>}
 {tab==='learning'&&<div className="detail-list">{enrollments.map(e=><article key={e.id}><div><b>{COURSES.find(x=>x.id===e.courseId)?.name}</b><Status value={e.cert}/></div><p>{e.cohort} · เข้าเรียน {e.attendance}% · ความคืบหน้า {e.progress}%</p><p>ข้อเขียน: {e.written?'ผ่าน':'รอผล'} · ปฏิบัติ: {e.practical?'ผ่าน':'รอผล'}</p><small>จัดส่ง: {e.tracking||'ยังไม่จัดส่ง'}</small></article>)}{!enrollments.length&&<Empty/>}</div>}
 {tab==='cases'&&<div className="detail-list">{cases.map(x=><article key={x.id}><div><b>{x.title}</b><Status value={x.status}/></div><small>{x.id} · {x.owner} · ครบกำหนด {dateTH(x.due)}</small></article>)}{!cases.length&&<Empty/>}</div>}
 {tab==='messages'&&<div className="messages-mini">{state.messages.filter(m=>m.customerId===c.id).map(m=><div className={'message '+m.direction} key={m.id}><p>{m.text}</p><small>{dateTH(m.time)} · {m.direction==='out'?'จำลองการส่ง':'รับแล้ว'}</small></div>)}</div>}
 {tab==='files'&&<div className="detail-list">{invoices.map(i=><article key={i.id}><b>{i.kind} · {i.id}</b><p>เอกสารตัวอย่างในระบบ</p></article>)}{state.payments.filter(p=>invoices.some(i=>i.id===p.invoiceId)&&p.slip).map(p=><article key={p.id}><b>สลิป · {p.id}</b><p>{p.slip}</p></article>)}{cases.flatMap(x=>x.attachments).map((f,i)=><article key={i}>{f}</article>)}{!invoices.length&&!cases.some(x=>x.attachments.length)&&<Empty/>}</div>}
 {tab==='tasks'&&<div className="detail-list">{state.tasks.filter(t=>t.customerId===c.id).map(t=><article key={t.id}><b>{t.title}</b><small>{dateTH(t.due)} {t.time} · {t.owner} · {t.done?'เสร็จแล้ว':'รอดำเนินการ'}</small></article>)}</div>}
 {tab==='history'&&<div className="timeline">{state.audit.filter(a=>a.entity===c.id||[...invoices,...leads,...cases,...enrollments].some(x=>x.id===a.entity)).map(a=><article key={a.id}><i/><b>{a.action}</b><p>{a.actor} · {dateTH(a.date)}</p><small>{a.entity}</small></article>)}<article><i/><b>สร้างโปรไฟล์ลูกค้า</b><p>{dateTH(c.created)} · ข้อมูลตัวอย่าง</p></article></div>}
 </div>{edit&&<FormModal title="แก้ไขข้อมูลลูกค้า" fields={fields} onClose={()=>setEdit(false)} onSave={v=>{const dupe=duplicateCustomer(state.customers,{name:v.name,phone:v.phone,email:v.email},c.id);if(dupe)throw Error(`ข้อมูลตรงกับ ${dupe.name} (${dupe.id})`);mutate('แก้ไขข้อมูลลูกค้า',c.id,s=>Object.assign(s.customers.find(x=>x.id===c.id)!,v,{age:Number(v.age),guardianConsent:v.guardianConsent==='yes'}));toast.success('อัปเดตโปรไฟล์แล้ว');}}/>}
 {merge&&<FormModal title="รวมโปรไฟล์ลูกค้า" description={`เก็บ ${c.name} เป็นโปรไฟล์หลัก และย้ายประวัติจากโปรไฟล์ที่เลือก`} fields={[{key:'source',label:'โปรไฟล์ที่จะรวม',options:customers.filter(x=>x.id!==c.id).map(x=>({value:x.id,label:`${x.name} (${x.id})`})),required:true},{key:'confirm',label:'พิมพ์ MERGE เพื่อยืนยัน',required:true}]} onClose={()=>setMerge(false)} onSave={v=>{if(v.confirm!=='MERGE')throw Error('กรุณาพิมพ์ MERGE');const from=customers.find(x=>x.id===v.source)!;if(c.peakId&&from.peakId&&c.peakId!==from.peakId)throw Error('มีรหัส PEAK ต่างกัน กรุณาตรวจ mapping กับฝ่ายบัญชีก่อน');mutate('รวมโปรไฟล์',c.id,s=>{for(const key of ['leads','cases','invoices','enrollments','tasks','messages','memberships','jobs'] as const){for(const row of s[key])if(row.customerId===from.id)row.customerId=c.id;}const target=s.customers.find(x=>x.id===c.id)!;target.tags=[...new Set([...target.tags,...from.tags])];target.peakId||=from.peakId;target.lineId||=from.lineId;target.consent=target.consent&&from.consent;target.notes+=`\nรวม ${from.id}: ${from.notes}`;s.customers.find(x=>x.id===from.id)!.archived=true;});toast.success('รวมประวัติและเก็บโปรไฟล์ต้นทางใน archive แล้ว');}}/>}
 </SheetContent></Sheet>;
}
