'use client';
import { DEMO_DATE,baht,certificateReady } from '@/lib/crm/domain';
import { ArrowRight,ArrowUpRight,Award,CalendarDays,Plus,Target,Users,Wallet } from 'lucide-react';
import { useState } from 'react';
import { Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis } from 'recharts';
import { useCRM } from './store';
import { Avatar,Button,Checkbox,Panel,Pick,Pill,Stat,Title } from './ui';
export default function Dashboard({createCustomer}:{createCustomer:()=>void}){
 const{state,customers,finance,go,mutate,inspect,role}=useCRM();const[period,setPeriod]=useState('month');
 const ids=new Set(customers.map(c=>c.id)),invoices=state.invoices.filter(i=>ids.has(i.customerId));
 const payments=state.payments.filter(p=>p.status==='Success'&&invoices.some(i=>i.id===p.invoiceId)&&(period==='month'||p.date>='2026-09-22'));
 const total=payments.reduce((n,p)=>n+p.amount,0),leads=state.leads.filter(l=>ids.has(l.customerId)&&!l.lostReason),tasks=state.tasks.filter(t=>ids.has(t.customerId));
 const graph=Array.from({length:period==='month'?28:7},(_,i)=>{const d=i+(period==='month'?1:22),date=`2026-09-${String(d).padStart(2,'0')}`;return{day:String(d),revenue:payments.filter(p=>p.date<=date).reduce((s,p)=>s+p.amount,0)};});
 const stats=[{label:finance?'ยอดรับชำระเดือนนี้':'ลูกค้าที่ดูแล',value:finance?baht(total):String(customers.length),detail:finance?<><Pill tone="green">{payments.length} รายการ</Pill><span>รับชำระแล้ว</span></>:<span>ตามขอบเขตสิทธิ์ของคุณ</span>,icon:<Wallet size={19}/>,page:finance?'finance':'customers',tone:'purple'}, {label:'ลูกค้าใหม่',value:customers.filter(c=>period==='month'||c.created>='2026-09-22').length,detail:<><Pill tone="green">5 ช่องทาง</Pill><span>เชื่อมทุกการติดต่อ</span></>,icon:<Users size={19}/>,page:'customers',tone:'blue'},{label:'โอกาสขายที่เปิดอยู่',value:leads.filter(l=>l.stage<9).length,detail:<><span>จาก Lead ถึงวันเรียนจบ</span></>,icon:<Target size={19}/>,page:'pipeline',tone:'orange'},{label:'พร้อมออกใบประกาศ',value:state.enrollments.filter(e=>ids.has(e.customerId)&&certificateReady(state,e)&&e.cert==='HIDE').length,detail:<><Pill tone="purple">รอดำเนินการ</Pill><span>ผ่านทุกเงื่อนไข</span></>,icon:<Award size={19}/>,page:'learning',tone:'teal'}];
 const won=leads.filter(l=>l.stage>=4).length,conversion=leads.length?Math.round(won/leads.length*100):0;
 return <><Title eyebrow="WORKSPACE OVERVIEW" title="ภาพรวมธุรกิจ" desc="เชื่อมทุกความสัมพันธ์ ดูแลทุกการเติบโต"><Pick label="ช่วงเวลา" value={period} onChange={setPeriod} options={[{value:'month',label:'กันยายน 2569'},{value:'week',label:'7 วันล่าสุดในเดโม'}]}/><Button onClick={createCustomer}><Plus size={17}/> เพิ่มลูกค้า</Button></Title>
 <div className="welcome-strip"><span className="welcome-symbol">✦</span><span><b>สวัสดี, ทีม Life Lab</b> <span className="welcome-detail">วันนี้มี {tasks.filter(t=>!t.done).length} กิจกรรมที่รอคุณดูแล</span></span><button onClick={()=>go('activities')}>ดูงานของวันนี้ <ArrowRight size={16}/></button></div>
 <div className="stats-grid">{stats.map(s=><Stat key={s.label} {...s} onClick={()=>go(s.page)}/>)}</div>
 <div className="dashboard-main"><Panel title={finance?'ภาพรวมรายรับ':'ภาพรวมความสัมพันธ์'} meta={finance?'ยอดรับชำระสะสม · กันยายน 2569':'ลูกค้าในความดูแลและแหล่งที่มา'} action={<button className="text-button" onClick={()=>go('reports')}>ดูรายงาน <ArrowUpRight size={16}/></button>}>
 {finance?<><div className="chart-summary"><strong>{baht(total)}</strong><Pill tone="purple">THB</Pill><span className="chart-legend"><i/> รับชำระสะสม</span></div><div className="revenue-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={graph} margin={{top:15,right:12,left:4,bottom:0}}><defs><linearGradient id="revenue-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#8666e6" stopOpacity={.24}/><stop offset="100%" stopColor="#8666e6" stopOpacity={.01}/></linearGradient></defs><CartesianGrid strokeDasharray="4 5" vertical={false} stroke="var(--border)"/><XAxis dataKey="day" axisLine={false} tickLine={false} minTickGap={45} tick={{fill:'var(--muted-foreground)',fontSize:12}} tickFormatter={v=>`${v} ก.ย.`}/><YAxis axisLine={false} tickLine={false} tick={{fill:'var(--muted-foreground)',fontSize:12}} tickFormatter={v=>`${v/1000}k`} width={43}/><Tooltip formatter={(v)=>[baht(Number(v)),'ยอดสะสม']} labelFormatter={v=>`${v} กันยายน 2569`} contentStyle={{borderRadius:12,border:'1px solid var(--border)',background:'var(--card)',color:'var(--foreground)'}}/><Area type="monotone" dataKey="revenue" stroke="#8765e6" strokeWidth={3} fill="url(#revenue-fill)"/></AreaChart></ResponsiveContainer></div></>:<div className="source-list">{['LINE OA','Facebook Ads','เว็บไซต์','Instagram','แนะนำโดยเพื่อน'].map(s=><div key={s}><span>{s}</span><div className="bar-track"><i style={{width:`${customers.filter(c=>c.source===s).length/Math.max(1,customers.length)*100}%`}}/></div><b>{customers.filter(c=>c.source===s).length}</b></div>)}</div>}
 <div className="chart-foot"><span>คำนวณจากธุรกรรมสถานะ Success ในช่วงเวลาที่เลือก</span><span>ข้อมูลจำลอง</span></div></Panel>
 <Panel title="จากความสนใจ สู่การเรียนรู้" meta="อัตราเปลี่ยน Lead เป็นผู้เรียน" className="conversion-panel"><div className="donut" style={{'--percent':`${conversion}%`} as React.CSSProperties}><div><span>Conversion rate</span><strong>{conversion}<small>%</small></strong><Pill tone="green">{won} โอกาสขาย</Pill></div></div><div className="conversion-key"><span><i className="dot purple"/> ชำระแล้ว / เรียน / จบ</span><b>{won}</b></div><div className="conversion-key"><span><i className="dot gray"/> อยู่ระหว่างการขาย</span><b>{leads.length-won}</b></div><button className="card-link" onClick={()=>go('pipeline')}>สำรวจ Sales Pipeline <ArrowRight size={17}/></button></Panel></div>
 <div className="dashboard-bottom"><Panel title="ลูกค้าที่ต้องติดตาม" meta="ดูแลต่อเนื่อง ไม่ให้พลาดโอกาสสำคัญ" action={<button className="text-button" onClick={()=>go('customers')}>ดูทั้งหมด <ArrowRight size={16}/></button>}><div className="follow-table"><div className="follow-header"><span>ลูกค้า / ความสนใจ</span><span>ช่องทาง</span><span>ผู้ดูแล</span><span>สถานะ</span></div>{leads.filter(l=>l.stage<4).slice(0,4).map(l=>{const c=customers.find(c=>c.id===l.customerId)!;return <button key={l.id} className="follow-row" onClick={()=>inspect(c.id)}><span className="person"><Avatar name={c.name}/><span><b>{c.name}</b><small>{l.next}</small></span></span><span className="source-tag">{c.source}</span><span>{c.owner}</span><Pill tone={l.lastContact<'2026-09-25'?'orange':'purple'}>{l.lastContact<'2026-09-25'?'ควรติดตาม':'กำลังดูแล'}</Pill></button>;})}</div></Panel>
 <Panel title="กิจกรรมวันนี้" meta="จันทร์ 28 กันยายน 2569" action={<button className="icon-button" aria-label="ดูกิจกรรม" onClick={()=>go('activities')}><ArrowUpRight size={18}/></button>}><div className="today-tasks">{tasks.slice(0,4).map(t=><div className={'task-row '+(t.done?'done':'')} key={t.id}><Checkbox aria-label={`ทำเสร็จ ${t.title}`} checked={t.done} onCheckedChange={v=>mutate('อัปเดตกิจกรรม',t.id,s=>{s.tasks.find(x=>x.id===t.id)!.done=!!v;})}/><div><b>{t.title}</b><small>{t.time} <span>· {customers.find(c=>c.id===t.customerId)?.nickname}</span></small></div>{t.due<DEMO_DATE&&!t.done&&<span className="overdue-dot" title="เกินกำหนด"/>}</div>)}</div><button className="card-link" onClick={()=>go('activities')}>เปิดปฏิทินกิจกรรม <CalendarDays size={16}/></button></Panel></div>
 <div className="dashboard-footer"><span><span className="status-dot"/> ข้อมูลเดโมบันทึกเฉพาะเบราว์เซอร์นี้</span><span>LifeLab Workspace <span> / </span> {role}</span></div></>;
}
