'use client';
import { processPeakJob,queuePeak } from '@/lib/crm/actions';
import { dateTH } from '@/lib/crm/domain';
import { ArrowRight,ExternalLink,Link2,Plug,RefreshCw,Settings2,ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import { toast } from 'sonner';
import { useCRM } from './store';
import { Button,Cell,DataTable,Empty,FormModal,Panel,Pick,Pill,Row,Status,TabBar,Title } from './ui';
export default function Integrations(){
 const{state,customers,mutate,role}=useCRM();const[tab,setTab]=useState('queue'),[filter,setFilter]=useState('all'),[modal,setModal]=useState(''),[checking,setChecking]=useState(false);const allowed=role==='ผู้บริหาร'||role==='System Admin'||role==='หัวหน้าบัญชี';const jobs=state.jobs.filter(j=>filter==='all'||j.status===filter);
 const retry=(id:string)=>{mutate('จำลอง PEAK sync',id,s=>processPeakJob(s,id));toast.success('ประมวลผลคิวเดโมแล้ว ตรวจสถานะในรายการ');};
 const test=async()=>{setChecking(true);try{if(process.env.NEXT_PUBLIC_STATIC_DEMO==='true'){toast.info('GitHub Pages Demo · จำลองการเชื่อมต่อ PEAK ใน browser ไม่มี live API');return;}const r=await fetch('/api/integrations/peak');if(!r.ok)throw Error('ตรวจสถานะ API ไม่สำเร็จ');const data=await r.json() as {message:string};toast.info(data.message);}catch(e){toast.error((e as Error).message);}finally{setChecking(false);}};
 return <><Title eyebrow="CONNECTED WORKSPACE" title="การเชื่อมต่อ" desc="ให้ข้อมูลไหลต่อกัน พร้อมตรวจสอบทุกขั้นตอน"><Button variant="outline" onClick={()=>setModal('guide')}><Settings2 size={16}/> ตั้งค่าการเชื่อมต่อ</Button><Button onClick={test} disabled={checking}><Plug size={16}/>{checking?'กำลังตรวจสอบ...':'ตรวจสถานะ API'}</Button></Title><div className="integration-hero"><div className="peak-logo">PEAK<span>ACCOUNT</span></div><div className="integration-hero-copy"><div><h2>PEAK Account</h2><Pill tone="purple">Demo mode</Pill></div><p>เชื่อมลูกค้า ใบเสนอราคา ใบแจ้งหนี้ และการรับชำระ</p><small>ยังไม่ได้เชื่อมบัญชีจริง · ไม่ส่งเอกสารหรือยอดเงินออกจากเดโม</small></div><div className="integration-hero-stats"><strong>{state.jobs.filter(j=>j.status==='Success').length}<small>ซิงก์จำลองแล้ว</small></strong><strong>{state.jobs.filter(j=>j.status==='Error').length}<small>ต้องตรวจสอบ</small></strong></div></div><div className="integration-flow"><span><UsersIcon/> Customer 360</span><ArrowRight size={17}/><span><FileIcon/> เอกสาร / รับชำระ</span><ArrowRight size={17}/><span><RefreshCw size={17}/> Queue + Idempotency</span><ArrowRight size={17}/><span className="peak-flow">PEAK Account</span></div><TabBar value={tab} onChange={setTab} items={[{id:'queue',label:'คิวซิงก์และข้อผิดพลาด'},{id:'mapping',label:'Customer mapping'},{id:'rules',label:'กฎและ Field mapping'},{id:'other',label:'ระบบอื่น ๆ'}]}/>
 {tab==='queue'&&<Panel><div className="toolbar"><Pick label="สถานะซิงก์" value={filter} onChange={setFilter} options={[{value:'all',label:'ทุกสถานะ'},{value:'Queued',label:'รอซิงก์'},{value:'Success',label:'สำเร็จ'},{value:'Error',label:'ข้อผิดพลาด'}]}/><span className="muted toolbar-spacer">ทุกงานมี key ป้องกันซ้ำ</span><Button variant="outline" disabled={!allowed||!state.jobs.some(j=>j.status!=='Success')} onClick={()=>{mutate('ประมวลผล PEAK batch เดโม','peak-batch',s=>{for(const j of s.jobs.filter(j=>j.status!=='Success'))processPeakJob(s,j.id);});toast.success('ประมวลผลคิวที่ค้างแล้ว');}}><RefreshCw size={15}/> ซิงก์งานค้าง</Button></div><DataTable heads={['งาน / เอกสาร','ลูกค้า','สถานะ','ความพยายาม','External ID / Error','จัดการ']}>{jobs.map(j=><Row key={j.id}><Cell><b>{j.entityId}</b><small className="block muted">{j.type} · {j.provider}</small><code>{j.key}</code></Cell><Cell>{customers.find(c=>c.id===j.customerId)?.name||j.customerId}</Cell><Cell><Status value={j.status}/></Cell><Cell>{j.attempts} ครั้ง</Cell><Cell>{j.error?<span className="text-red">{j.error}</span>:<span className="external-id">{j.externalId||'—'}</span>}<small className="block muted">{dateTH(j.date)}</small></Cell><Cell><Button size="sm" variant="outline" onClick={()=>retry(j.id)} disabled={!allowed||j.status==='Success'}><RefreshCw size={14}/>{j.status==='Error'?'Retry':'ซิงก์'}</Button></Cell></Row>)}</DataTable>{!jobs.length&&<Empty/>}</Panel>}
 {tab==='mapping'&&<Panel title="ลูกค้า CRM ↔ PEAK" meta="ต้องมีรหัสลูกค้า PEAK ก่อนสร้าง Hosted Payment"><DataTable heads={['ลูกค้า','CRM ID','PEAK ID','สถานะ','การดำเนินการ']}>{customers.map(c=><Row key={c.id}><Cell>{c.name}</Cell><Cell>{c.id}</Cell><Cell><code>{c.peakId||'—'}</code></Cell><Cell><Pill tone={c.peakId?'green':'orange'}>{c.peakId?'เชื่อมในเดโม':'ยังไม่เชื่อม'}</Pill></Cell><Cell><Button variant="outline" size="sm" disabled={!!c.peakId||!allowed} onClick={()=>{mutate('สร้าง PEAK contact เดโม',c.id,s=>{const job=queuePeak(s,c.id,c.id,'Contact');processPeakJob(s,job.id);});toast.success('สร้าง Customer mapping เดโมแล้ว');}}><Link2 size={14}/> เชื่อมลูกค้า</Button></Cell></Row>)}</DataTable></Panel>}
 {tab==='rules'&&<div className="two-col"><Panel title="Field mapping" meta="ตัวอย่างสำหรับ review ก่อนเชื่อม Sandbox"><DataTable heads={['CRM','PEAK / เป้าหมาย','Source of truth']}>{[['customer.id','Contact reference / mapping key','CRM'],['customer.name','Contact name','CRM'],['customer.peakId','Contact id','PEAK'],['invoice.id','Invoice reference','CRM'],['invoice.total','Invoice net amount','อนุมัติจากฝ่ายบัญชี'],['payment.reference','Payment mapping key','ผู้ให้บริการชำระเงิน'],['enrollment.progress','LearnDash course progress','LearnDash']].map(r=><Row key={r[0]}>{r.map(v=><Cell key={v}>{v}</Cell>)}</Row>)}</DataTable></Panel><Panel title="กติกาการซิงก์"><div className="rule-list">{[['01','ส่งทุกครั้งที่รับชำระ','ไม่รอผ่อนครบ 50% — ทุกงวดสร้างงานแยก'],['02','ป้องกันรายการซ้ำ','คีย์ประกอบด้วยชนิดเอกสาร + รหัสรายการ'],['03','Retry อย่างตรวจสอบได้','แสดงจำนวนครั้ง ข้อผิดพลาด และผลลัพธ์'],['04','Batch สำรอง 20:00 น.','เดโมใช้ปุ่มซิงก์งานค้างแทนตัวตั้งเวลา'],['06','2C2P และแจ้งชำระอัตโนมัติ','หน้า การเงิน → 2C2P และแจ้งเตือน จำลองดึงลิงก์จาก PEAK แล้วแจ้ง Email + SMS'],['05','Token อยู่ฝั่ง Server','ใช้ HMAC-SHA1, Client Token และ User Token']].map(([n,t,d])=><article key={n}><span>{n}</span><div><b>{t}</b><p>{d}</p></div></article>)}</div></Panel></div>}
 {tab==='other'&&<div className="other-integrations">{[['LINE OA','บทสนทนา, Webhook และการแจ้งเตือน','LINE'],['2C2P','Hosted Payment · Visa / Mastercard','2C2P'],['WooCommerce','Customer / Order / Product ผ่าน REST API','WOO'],['LearnDash','การลงทะเบียนและความคืบหน้าการเรียน','LD'],['SMS OTP','ผู้ให้บริการและข้อกำหนดยังรอยืนยัน','OTP'],['HubSpot','แหล่งนำเข้าข้อมูลเก่า · ไม่ใช่ sync ต่อเนื่อง','HS']].map(([name,desc,mark])=><Panel className="integration-card" key={name}><div className={'integration-mark mark-'+mark}>{mark}</div><h2>{name}</h2><p>{desc}</p><Pill>ยังไม่เชื่อมระบบจริง</Pill><Button variant="outline" onClick={()=>setModal(name)}>ดูขอบเขตการเชื่อมต่อ <ArrowRight size={15}/></Button></Panel>)}</div>}
 {modal&&<FormModal title={modal==='guide'?'ตั้งค่า PEAK Account':modal} description="การเชื่อมต่อจริงต้องใช้บัญชีทดสอบและสิทธิ์ที่ได้รับอนุมัติ" fields={[]} onSave={()=>{}} submit="เข้าใจแล้ว" onClose={()=>setModal('')}><div className="connection-guide">{modal==='guide'?<><p>เตรียม Connect ID, Password และ User Token จาก PEAK แล้วตั้งค่าในสภาพแวดล้อมฝั่ง Server ตามคู่มือในโครงการ</p><div className="config-lines"><code>PEAK_BASE_URL</code><code>PEAK_CONNECT_ID</code><code>PEAK_PASSWORD</code><code>PEAK_USER_TOKEN</code><code>PEAK_SIGNATURE_ENCODING</code></div><p>เดโมมี server adapter สำหรับขอ Token และอ่านข้อมูล แต่ยังไม่เปิด live endpoint หรือบันทึกบัญชีจริง</p><a href="https://developers.peakaccount.com/reference/peak-api-client-token-guide" target="_blank" rel="noreferrer">คู่มือ PEAK API ทางการ <ExternalLink size={14}/></a></>:<><p>ส่วนนี้แสดงกระบวนการและสถานะจำลองตาม Requirement เพื่อเตรียมเชื่อมต่อ {modal}</p><p>ต้องตั้งค่า credential, ตรวจ signature และทดสอบ duplicate event / retry ใน UAT ก่อนใช้งานจริง</p></>}</div></FormModal>}
 </>;
}
function UsersIcon(){return <ShieldCheck size={17}/>;}function FileIcon(){return <Link2 size={17}/>;}
