'use client';
import { useState } from 'react';
import { toast } from 'sonner';
import { baht,balanceFor } from '@/lib/crm/domain';
import { DemoScenario,linkUsable,requestDemoPaymentLink,retryDemoDelivery } from '@/lib/crm/payment-links';
import { useCRM } from './store';
import { Button,Cell,DataTable,Empty,FormModal,Panel,Pill,Row } from './ui';
export default function PaymentLinks(){
 const{state,customers,mutate}=useCRM();const[modal,setModal]=useState(false),[preview,setPreview]=useState('');
 const invoices=state.invoices.filter(i=>i.kind==='Invoice'&&customers.some(c=>c.id===i.customerId));
 const links=state.paymentLinks.filter(l=>invoices.some(i=>i.id===l.invoiceId));
 const deliveries=state.deliveries.filter(d=>links.some(l=>l.id===d.linkId));
 const selected=links.find(l=>l.id===preview);
 const run=(id:string,scenario:DemoScenario)=>{requestDemoPaymentLink(structuredClone(state),id,scenario);mutate('ดึงลิงก์ PEAK และแจ้ง Email SMS เดโม',id,s=>{requestDemoPaymentLink(s,id,scenario);});toast.info('ประมวลผลอัตโนมัติแล้ว ดูผลลิงก์และการแจ้งเตือนด้านล่าง');};
 return <><div className="info-box"><b>PEAK → ลิงก์ 2C2P → Email + SMS อัตโนมัติ</b><p>เลือกวิธีชำระ 2C2P ระบบตรวจรหัสลูกค้าและใบแจ้งหนี้ PEAK แล้วจำลองดึงลิงก์และส่งแจ้งเตือนทั้งสองช่องทาง ไม่ต้องคัดลอกลิงก์เอง</p><p>Demo: ไม่มีการส่งข้อความหรือตัดเงินจริง · URL ตัวอย่างใช้โดเมน .invalid · การเชื่อมจริงรอ PEAK ยืนยัน API Payment Link</p></div>
 <div className="section-actions"><div><h2>ลิงก์ชำระเงินจาก PEAK</h2><p className="muted">ลิงก์เดโมมีอายุ 24 ชั่วโมง · ส่งซ้ำไม่เพิ่มข้อความที่สำเร็จแล้ว</p></div><Button onClick={()=>setModal(true)}>เลือกชำระ 2C2P</Button></div>
 <Panel><DataTable heads={['ใบแจ้งหนี้ / ลูกค้า','ยอด / แหล่งข้อมูล','ลิงก์ / หมดอายุ','สถานะ','จัดการ']}>{links.map(l=><Row key={l.id}><Cell><b>{l.invoiceId}</b><small className="block muted">{customers.find(c=>c.id===l.customerId)?.name}</small></Cell><Cell>{baht(l.amount)}<small className="block muted">PEAK → 2C2P · Demo</small></Cell><Cell><span className="payment-url">{l.url||'ยังไม่ได้รับลิงก์'}</span><small className="block muted">{l.expiresAt?new Date(l.expiresAt).toLocaleString('th-TH'):'—'}</small></Cell><Cell><Pill tone={linkUsable(state,l)?'green':'orange'}>{l.status==='Ready'?(linkUsable(state,l)?'พร้อมใช้ในเดโม':'หมดอายุ / ยอดเปลี่ยน'):l.status}</Pill>{l.error&&<small className="block text-red">{l.error}</small>}<small className="block muted">ดึง {l.attempts} ครั้ง</small></Cell><Cell><div className="row-actions"><Button size="sm" variant="outline" disabled={!linkUsable(state,l)} onClick={()=>setPreview(l.id)}>ดูหน้าชำระจำลอง</Button>{l.status==='Error'&&<Button size="sm" onClick={()=>{try{run(l.invoiceId,'success');}catch(e){toast.error((e as Error).message);}}}>ลองดึงใหม่</Button>}</div></Cell></Row>)}</DataTable>{!links.length&&<Empty text="เลือกชำระ 2C2P เพื่อเริ่ม flow อัตโนมัติ"/>}</Panel>
 <Panel title="ประวัติ Email และ SMS" meta="DemoSent หมายถึงจำลองส่งสำเร็จ ยังไม่มีการส่งออกไปยังลูกค้าจริง"><DataTable heads={['ช่องทาง / ผู้รับ','ข้อความแจ้งชำระ','สถานะ / จำนวนครั้ง','ดำเนินการ']}>{deliveries.map(d=><Row key={d.id}><Cell><b>{d.channel}</b><small className="block payment-url">{d.recipient||'ไม่มีข้อมูลติดต่อ'}</small></Cell><Cell><p className="payment-message">{d.body}</p></Cell><Cell><Pill tone={d.status==='DemoSent'?'green':'orange'}>{d.status==='DemoSent'?'ส่งสำเร็จ (จำลอง)':'ส่งไม่สำเร็จ'}</Pill><small className="block muted">{d.attempts} ครั้ง</small>{d.error&&<small className="block text-red">{d.error}</small>}</Cell><Cell><Button size="sm" variant="outline" disabled={d.status==='DemoSent'||!links.some(l=>l.id===d.linkId&&linkUsable(state,l))} onClick={()=>{try{retryDemoDelivery(structuredClone(state),d.id);mutate('Retry แจ้งชำระเดโม',d.id,s=>retryDemoDelivery(s,d.id));toast.info('ลองส่งช่องทางที่ล้มเหลวแล้ว');}catch(e){toast.error((e as Error).message);}}}>ลองส่งใหม่</Button></Cell></Row>)}</DataTable>{!deliveries.length&&<Empty text="เมื่อได้รับลิงก์ ระบบจะบันทึกการแจ้งเตือนอัตโนมัติ"/>}</Panel>
 {modal&&<FormModal title="เลือกวิธีชำระ 2C2P" description="เมื่อบันทึก ระบบดึงลิงก์จาก PEAK แล้วแจ้ง Email และ SMS ให้อัตโนมัติในโหมดเดโม" submit="บันทึกและเริ่มอัตโนมัติ" onClose={()=>setModal(false)} fields={[{key:'invoiceId',label:'ใบแจ้งหนี้',required:true,options:invoices.filter(i=>balanceFor(state,i.id)>0).map(i=>({value:i.id,label:`${i.id} · ${customers.find(c=>c.id===i.customerId)?.name} · ${baht(balanceFor(state,i.id))}`}))},{key:'scenario',label:'สถานการณ์สำหรับนำเสนอ',value:'success',options:[{value:'success',label:'PEAK ส่งลิงก์กลับมาและแจ้งสำเร็จ'},{value:'peak-error',label:'PEAK ไม่พร้อม ยังไม่ส่งข้อความ'},{value:'sms-error',label:'ได้รับลิงก์ Email สำเร็จ แต่ SMS ล้มเหลว'}]}]} onSave={v=>run(v.invoiceId,v.scenario as DemoScenario)}/>}
 {selected&&<FormModal title="หน้าชำระเงินจำลอง" description="ตัวอย่างปลายทางเมื่อลูกค้ากดลิงก์ ไม่เชื่อมต่อผู้ให้บริการจริง" fields={[]} onClose={()=>setPreview('')} onSave={()=>setPreview('')} submit="ปิดหน้าตัวอย่าง"><div className="connection-guide"><Pill tone="purple">LifeLab · 2C2P Demo</Pill><h2>{baht(selected.amount)}</h2><p>ใบแจ้งหนี้ {selected.invoiceId}</p><p>แหล่งลิงก์: PEAK · รองรับแนวทาง Hosted Payment</p><p>ไม่มีช่องกรอกบัตรและไม่มีการเรียกเก็บเงินจริง การเปิดลิงก์หรือส่งข้อความไม่เปลี่ยนยอดชำระ</p><p className="muted">เมื่อเชื่อมระบบจริง ลูกค้าจะชำระในหน้าของผู้ให้บริการ และ CRM ต้องตรวจสอบผลชำระจาก backend ก่อนบันทึก Success</p></div></FormModal>}
 </>;
}
