'use client';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog,DialogContent,DialogDescription,DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';
import { Tabs,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { ArrowUpRight,Inbox,Search } from 'lucide-react';
import { ReactNode,useState } from 'react';
import { toast } from 'sonner';
export { Button,Checkbox,Input };
export function Pick({value,onChange,options,label,className=''}:{value:string;onChange:(v:string)=>void;options:(string|{value:string;label:string})[];label:string;className?:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className={'pick '+className} aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={typeof o==='string'?o:o.value} value={typeof o==='string'?o:o.value}>{typeof o==='string'?o:o.label}</SelectItem>)}</SelectContent></Select>;}
export function Pill({children,tone='neutral'}:{children:ReactNode;tone?:string}){return <span className={'pill '+tone}>{children}</span>;}
export function Status({value}:{value:string}){const tones:Record<string,string>={Success:'green',Paid:'green',Active:'green',SHOW:'green',Resolved:'green',Closed:'neutral',Pending:'orange',Partial:'orange',New:'purple','In Progress':'blue','Waiting for Customer':'orange',Error:'red',Failed:'red',Rejected:'red',HIDE:'neutral',Queued:'orange',Demo:'purple',Received:'green',Shipped:'blue',Approved:'green'};const labels:Record<string,string>={Success:'สำเร็จ',Paid:'ชำระครบ',Active:'ใช้งาน',SHOW:'แสดงใบประกาศ',Resolved:'แก้ไขแล้ว',Closed:'ปิดเคส',Pending:'รอตรวจสอบ',Partial:'ชำระบางส่วน',New:'เคสใหม่','In Progress':'กำลังดำเนินการ','Waiting for Customer':'รอลูกค้า',Error:'ต้องตรวจสอบ',Failed:'ไม่สำเร็จ',Rejected:'ปฏิเสธ',HIDE:'ยังไม่ปลดล็อก',Queued:'รอซิงก์',Demo:'จำลองการส่ง',Received:'รับแล้ว',Shipped:'จัดส่งแล้ว',Approved:'อนุมัติแล้ว'};return <Pill tone={tones[value]||'neutral'}>{labels[value]||value}</Pill>;}
export function Avatar({name,size='normal'}:{name:string;size?:string}){const n=Array.from(name).reduce((s,c)=>s+c.charCodeAt(0),0);return <span className={`avatar ${size} av-${n%5}`}>{name.slice(0,1)}</span>;}
export function Title({eyebrow,title,desc,children}:{eyebrow?:string;title:string;desc?:string;children?:ReactNode}){return <div className="page-title"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{desc&&<p>{desc}</p>}</div><div className="title-actions">{children}</div></div>;}
export function Panel({title,meta,action,children,className=''}:{title?:string;meta?:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={'panel '+className}>{title&&<div className="panel-head"><div><h2>{title}</h2>{meta&&<p>{meta}</p>}</div>{action}</div>}{children}</section>;}
export function Stat({label,value,detail,icon,tone='purple',onClick}:{label:string;value:ReactNode;detail:ReactNode;icon:ReactNode;tone?:string;onClick?:()=>void}){return <button className="stat" onClick={onClick}><div className="stat-top"><span>{label}</span><span className={'stat-icon '+tone}>{icon}</span></div><strong>{value}</strong><div className="stat-bottom">{detail}<ArrowUpRight size={16}/></div></button>;}
export function DataTable({heads,children}:{heads:string[];children:ReactNode}){return <div className="data-table"><Table><TableHeader><TableRow>{heads.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{children}</TableBody></Table></div>;}
export { TableCell as Cell,TableRow as Row };
export function SearchBox({value,onChange,placeholder='ค้นหา...'}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <div className="searchbox"><Search size={17}/><Input aria-label={placeholder} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>;}
export function Empty({text='ยังไม่มีรายการที่ตรงกับเงื่อนไข'}:{text?:string}){return <div className="empty"><Inbox size={30}/><p>{text}</p></div>;}
export function TabBar({value,onChange,items}:{value:string;onChange:(v:string)=>void;items:{id:string;label:string}[]}){return <Tabs value={value} onValueChange={onChange}><TabsList variant="line" className="tabbar">{items.map(t=><TabsTrigger value={t.id} key={t.id}>{t.label}</TabsTrigger>)}</TabsList></Tabs>;}
export type Field={key:string;label:string;type?:string;value?:string|number;options?:(string|{value:string;label:string})[];required?:boolean;min?:number;max?:number;full?:boolean;help?:string};
export function FormModal({title,description,fields,onSave,submit='บันทึกข้อมูล',onClose,children}:{title:string;description?:string;fields:Field[];onSave:(v:Record<string,string>)=>void|Promise<void>;submit?:string;onClose:()=>void;children?:ReactNode}){
 const[values,setValues]=useState<Record<string,string>>(Object.fromEntries(fields.map(f=>[f.key,String(f.value??'')]))),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <Dialog open onOpenChange={v=>{if(!v)onClose();}}><DialogContent className="form-modal"><DialogTitle>{title}</DialogTitle><DialogDescription>{description||'กรอกข้อมูลเพื่อบันทึกในเดโมนี้'}</DialogDescription><form onSubmit={async e=>{e.preventDefault();setError('');setBusy(true);try{for(const f of fields)if(f.required&&!values[f.key]?.trim())throw Error(`กรุณาระบุ ${f.label}`);await onSave(values);onClose();}catch(err){setError(err instanceof Error?err.message:'บันทึกไม่สำเร็จ');}finally{setBusy(false);}}}><div className="form-grid">{fields.map(f=><label key={f.key} className={f.full?'full':''}><span>{f.label}{f.required&&<b className="required"> *</b>}</span>{f.options?<Pick label={f.label} value={values[f.key]} onChange={v=>setValues({...values,[f.key]:v})} options={f.options}/>:f.type==='textarea'?<textarea aria-label={f.label} value={values[f.key]} onChange={e=>setValues({...values,[f.key]:e.target.value})} required={f.required}/>:<Input aria-label={f.label} type={f.type||'text'} value={values[f.key]} onChange={e=>setValues({...values,[f.key]:e.target.value})} required={f.required} min={f.min} max={f.max} step={f.type==='number'?'0.01':undefined}/>} {f.help&&<small>{f.help}</small>}</label>)}</div>{children}{error&&<div role="alert" className="form-error">{error}</div>}<div className="form-actions"><Button variant="outline" type="button" onClick={onClose}>ยกเลิก</Button><Button type="submit" disabled={busy}>{busy?'กำลังบันทึก...':submit}</Button></div></form></DialogContent></Dialog>;
}
export function exportCSV(name:string,heads:string[],rows:(string|number|boolean)[][]){const cell=(v:unknown)=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};download(name+'.csv','\uFEFF'+[heads,...rows].map(r=>r.map(cell).join(',')).join('\r\n'),'text/csv;charset=utf-8');toast.success('ส่งออก CSV แล้ว');}
export function download(name:string,content:string,mime='application/json'){const url=URL.createObjectURL(new Blob([content],{type:mime}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
